spring.application.name=EcommerceWebsite
spring.datasource.url=jdbc:mysql://localhost:3306/ecommerce
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

paypal.client.id=AQXh9Kf7sL3nPqR8vYt6WbC2D1E4F5G6H7J8K9L0M1N2O3P4Q5R6S7T8
paypal.client.secret=EJd93kLmNoPqRsTuVwXyZ1234567890AbCdEfGhIjKlMnOpQrStUvWxYz
paypal.mode=sandbox

